config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :pledges
  end
  root 'projects#index'

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  validates :name, presence: true

  validates :email, format: { with: /(\S+)@(\S+)/ }

  PLEDGE_AMOUNT_OPTIONS = [
    5, 10, 15, 25, 50, 100, 200, 500
  ]

  validates :pledge_amount, inclusion: { in: PLEDGE_AMOUNT_OPTIONS }

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, :website, :team_members, presence: true
  validates :description, length: {minimum: 20}
  validates :target_pledge_amount, numericality: {greater_than_or_equal_to: 0,  message: "%{value}must be greater than zero." }
  validates :image_file_name, allow_blank: true, format: {
    with: /\w+|.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  validates :pledging_ends_on,
    date: { after: Proc.new { Date.today }, message: 'must be after today' }


  has_many :pledges, dependent: :destroy #destroys all pledges when project is destroyed

  def expired?
     pledging_ends_on.past?
  end

  def blank?
    pledging_ends_on.blank?
  end

  def more_29_days?
    end_date = pledging_ends_on
    start_date = Time.now
    ( end_date.to_date - start_date.to_date ).to_i > 29
  end

  def self.actual
    where("pledging_ends_on >= ?", Time.now).order(pledging_ends_on: :asc)
  end

  def funded_percentage
    (1 -(target_pledge_amount - (pledges.map { |pledge| pledge[:pledge_amount]}.sum))/target_pledge_amount) * 100
  end

  def funded_amount
    pledges.map { |pledge| pledge[:pledge_amount]}.sum
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :set_pledge

  def index
    @pledges = @project.pledges
  end

  def new
    @pledge = @project.pledges.new
  end

  def create
    @pledge = @project.pledges.new(pledge_params)
    if @pledge.save
      redirect_to project_pledges_path(@project),
                  notice: "Thanks, your pledge has been received!"
    else
      render :new
    end

  end

private
  def pledge_params
    params.require(:pledge).permit(:name, :email, :pledge_amount, :comment)
  end

  def set_pledge
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.actual
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: "Event succesfully updated!"
    else
      render :edit
    end
  end

  def new
    @project = Project.new(params[:project])
  end

  def create
    @project = Project.new(project_params)
    if @project.save # this calls the valid? method if any errors messages than not save
      redirect_to @project
    else
      render :new # not redirect_to than you loose the data filled out already
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url
  end

private

  def project_params
    params.require(:project).permit(:name, :description, :target_pledge_amount, :website, :pledging_ends_on, :team_members, :image_file_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def pledging_ends_format(project)
    end_date = project.pledging_ends_on
    start_date = Time.now
    if project.blank?
      "<em>Date was kept blank</em>".html_safe
    elsif project.expired?
      "<strong><em>All Done!</em></strong>".html_safe + " #{(start_date.to_date - end_date.to_date).to_i} days ago"
    elsif project.more_29_days?
      "#{( end_date.to_date - start_date.to_date ).to_i} days remaining".html_safe
    else
      distance_of_time_in_words( project.pledging_ends_on, Time.now ) + " remaining".html_safe
    end
  end

  def image_for_show(project)
    if project.image_file_name.blank?
      image_tag("project_icon1.jpg", class: "image_tag_show")
    else
      image_tag(project.image_file_name, class: "image_tag_show")
    end
  end

  def image_for_index(project)
    if project.image_file_name.blank?
      image_tag("project_icon1.jpg", class: "image_tag_listing")
    else
      image_tag(project.image_file_name, class: "image_tag_listing")
    end
  end
end

app/views/layouts/_footer.html.erb
<footer id="page-footer" ,class="page-row">
<p>
  Copyright &copy; 2016
  <%= link_to 'Crowdfunding','http://www.crowdfunding.nl/' %>
</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
    <div id="masthead">
  <h1>Crowdfund projects</h1>
    </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-projects">
        <%= link_to "All projects", projects_path %>
      </li>
      <li class="create-project">
        <%= link_to "Add New Project", new_project_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfund</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<main class="page-row page-row-expanded">
<%= render "layouts/header" %>

<div id="wrapper">

    <% if flash[:notice] %>
    <p class="flash notice">
      <%= flash[:notice] %>
    </p>
    <% end %>

    <div id="container">
      <section id="sidebar">
        <%= render "layouts/sidebar" %>
      </section>
      <section id="content">
        <%= yield %>
      </section>
    </div>

</div>
</main>

  <%= render "layouts/footer" %>

</body>
</html>

app/views/pledges/index.html.erb
<header id="content-header">
  <h1>Pledges for <%= link_to(@project.name, @project) %></h1>
</header>

<ol id="pledges">
  <% @pledges.each do |pledge| %>
  <li>
    <%= mail_to(pledge.email, pledge.name.capitalize) %>
    <%= number_to_currency(pledge.pledge_amount, :unit => "EUR ", :precision => 0) %>
    <br/>
    Comment: <%= pledge.comment %>
  </li>

  <% end %>
</ol>

app/views/pledges/new.html.erb
<header id="content-header">
  <h1>Pledge for <%= link_to @project.name, @project %></h1>
</header>

<%= form_for([@project, @pledge]) do |f| %>
<%= render 'shared/errors', object: @pledge %>
<fieldset>
  <ol>
    <li class="required">
      <%= f.label :name %>
      <%= f.text_field :name, size: 40, autofocus: true %>
    </li>
    <li class="required">
      <%= f.label :email %>
      <%= f.text_field :email, size: 40 %>
    </li>
    <li class="required">
      <%= f.label :pledge_amount %>
      <%= f.select :pledge_amount,
                  Pledge::PLEDGE_AMOUNT_OPTIONS,
                  prompt: "Pick one" %>
    </li>
    <li class="required">
      <%= f.label :comment %>
      <%= f.text_area :comment, cols: 50, rows: 6 %>
    </li>
  </ol>
  <p>
    <%= f.submit %>
    <%= link_to "Cancel", project_path(@project), class: 'cancel' %>
  </p>
</fieldset>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= render "shared/errors", object: @project %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %><br/>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %><br/>
        <%= f.text_area :description, cols: 50, rows: 6 %>
      </li>
      <li class="required">
        <%= f.label :target_pledge_amount %><br/>
        <%= f.number_field :target_pledge_amount %>
      </li>
      <li class="required">
        <%= f.label :website %><br/>
        <%= f.text_field :website %>
      </li>
      <li class="required">
        <%= f.label :pledging_ends_on %><br/>
        <%= f.date_select :pledging_ends_on %>
      </li>
      <li class="required">
        <%= f.label :team_members %><br/>
        <%= f.text_field :team_members %>
      </li>
      <li>
        <%= f.label :image_file_name %><br/>
        <%= f.text_field :image_file_name %>
      </li>
    </ol>
    <p>
      <%= f.submit %> <%= link_to "Cancel", root_path, class: 'cancel' %>
    </p>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<header id="content-header">
<h1>Editing <%= @project.name %></h1>
</header>

<%= render "form" %>

app/views/projects/index.html.erb
<ul id="projects">
<h1><%= pluralize(@projects.length, "project") %></h1>

<% @projects.each do |project| %>
  <article class="project">
    <header>
      <%= image_for_index(project) %>
      <h2><%= link_to project.name, project %></h2>
    </header>
    <p>
      <%= truncate(project.description, length: 30, separator: ' ') %>
    </p>
    <table>
      <tr>
        <th>Target amount:</th>
        <td><%= number_to_currency(project.target_pledge_amount, :unit => "EUR ", :precision => 0) %></td>
      </tr>
      <tr>
        <th>Website:</th>
        <td><%= link_to project.website, 'http://'+ project.website %></td>
      </tr>
      <tr>
        <th>Pledging ends on:</th>
        <td><%= project.pledging_ends_on %></td>
      </tr>
      <tr>
        <th></th>
        <td><%= pledging_ends_format(project) %></td>
      </tr>
      <tr>
        <th>Team members:</th>
        <td><%= truncate(project.team_members, length: 10, separator: ' ') %></td>
      </tr>
    </table>
    <h3>
        <%= project.funded_percentage %> % Funded +
        <%= number_to_currency(project.funded_amount, :unit => "EUR ", :precision => 0) %> Pledged +
        <%= pluralize(project.pledges.count, "Backer") %>
    </h3>
  </article>
<% end %>

app/views/projects/new.html.erb
<header id="content-header">
  <h1>Add new project </h1>
</header>

<%= render "form" %>

app/views/projects/show.html.erb
  <article id="project" class="project">
    <header>
      <%= image_for_show(@project) %>
      <h2><%= @project.name %></h2>
    </header>

    <p>
      <%= @project.description %>
    </p>

    <table>
      <tr>
        <th>Target amount:</th>
        <td><%= number_to_currency(@project.target_pledge_amount, :unit => "EUR ", :precision => 0) %></td>
      </tr>
      <tr>
        <th>Website:</th>
        <td><%= @project.website %></td>
      </tr>
      <tr>
        <th>Pledging ends on:</th>
        <td><%= pledging_ends_format(@project) %></td>
      </tr>
      <tr>
        <th>Team members:</th>
        <td><%= @project.team_members %></td>
      </tr>
    </table>
    <p>
      <%= link_to "Who has made pledges?", project_pledges_path(@project) %>
    </p>
    <footer>
      <%= link_to "Make a pledge!", new_project_pledge_path(@project), class:"button ok register" %>
      <nav>
    <%= link_to "Edit", edit_project_path(@project), class: 'cancel' %>
    <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?"}, class: 'cancel' %>
      </nav>
    </footer>
  </article>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section id="errors">
    <header>
      <h2>
        Oops! Your form could not be saved.
      </h2>
      <h3>
        Please correct the following
        <%= pluralize(object.errors.count, "error") %>:
      </h3>
    </header>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>